package com.group16.stardewvalley.model.food;

public enum     Ingredient {
    EGG("Egg"),
    SARDINE("Sardine"),
    SALMON("Salmon"),
    WHEAT("Wheat"),
    LEEK("Leek"),
    DANDELION("Dandelion"),
    MILK("Milk"),
    PUMPKIN("Pumpkin"),
    WHEAT_FLOUR("Wheat Flour"),
    SUGAR("Sugar"),
    TOMATO("Tomato"),
    CHEESE("Cheese"),
    CORN("Corn"),
    FISH("Fish"),
    RICE("Rice"),
    FIBER("Fiber"),
    COFFEE("Coffee Bean"),
    BLUEBERRY("Blueberry"),
    MELON("Melon"),
    APRICOT("Apricot"),
    RED_CABBAGE("Red Cabbage"),
    RADISH("Radish"),
    AMARANTH("Amaranth"),
    KALE("Kale"),
    BEET("Beet"),
    OMELET("Omelet"),
    PARSNIP("Parsnip"),
    BREAD("Bread"),
    CARROT("Carrot"),
    EGGPLANT("Eggplant"),
    HASH_BROWN("Hashbrowns"),
    FLOUNDER("Flounder"),
    MIDNIGHT_CARP("Midnight Carp"),
    OIL ("Oil"),
    //new
    CHERRY("Cherry"),
    BANANA("Banana"),
    MANGO("Mango"),
    ORANGE("Orange"),
    PEACH("Peach"),
    APPLE("Apple"),
    POMEGRANATE("Pomegranate"),
    OAK_RESIN("Oak Resin"),
    MAPLE_SYRUP("Maple Syrup"),
    PINE_TAR("Pine Tar"),
    SAP("Sap"),
    COMMON_MUSHROOM("Common Mushroom"),
    MYSTIC_SYRUP("Mystic Syrup"),
    BLUE_JAZZ("Blue Jazz"),
    CAULIFLOWER("Cauliflower"),
    COFFEE_BEAN("Coffee Bean"),
    GARLIC("Garlic"),
    GREEN_BEAN("Green Bean"),
    POTATO("Potato"),
    RHUBARB("Rhubarb"),
    STRAWBERRY("Strawberry"),
    TULIP("Tulip"),
    UNMILLED_RICE("Unmilled Rice"),
    HOPS("Hops"),
    HOT_PEPPER("Hot Pepper"),
    POPPY("Poppy"),
    STARFRUIT("Starfruit"),
    SUMMER_SPANGLE("Summer Spangle"),
    SUMMER_SQUASH("Summer Squash"),
    SUNFLOWER("Sunflower"),
    ARTICHOKE("Artichoke"),
    BOK_CHOY("Bok Choy"),
    BROCCOLI("Broccoli"),
    CRANBERRIES("Cranberries"),
    FAIRY_ROSE("Fairy Rose"),
    GRAPE("Grape"),
    YAM("Yam"),
    SWEET_GEM_BERRY("Sweet Gem Berry"),
    POWDERMELON("Powdermelon"),
    ANCIENT_FRUIT("Ancient Fruit"),

    // Crafting Ingredients
    COAL("Coal"),
    COPPER_ORE("Copper Ore"),
    IRON_ORE("Iron Ore"),
    GOLD_ORE("Gold Ore"),
    IRIDIUM_ORE("Iridium Ore"),
    COPPER_BAR("Copper Bar"),
    IRON_BAR("Iron Bar"),
    GOLD_BAR("Gold Bar"),
    IRIDIUM_BAR("Iridium Bar"),
    WOOD("Wood"),
    STONE("Stone"),
    ACORN("Acorn"),
    MAPLE_SEED("Maple Seed"),
    PINE_CONE("Pine Cone"),
    MAHOGANY_SEED("Mahogany Seed");


    private final String name;

    Ingredient(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
